backend:
  name: github
  repo: username/repo
  branch: main
  site_domain: https://www.taruol.cn
  base_url: https://www.taruol.cn
  auth_endpoint: /api/auth
media_folder: src/assets/images
public_folder: src/assets/images
collections:
  - name: "blog" # 用于路由，例如，/admin/collections/blog
    label: "blog" # 在 UI 中使用
    folder: "src/content/blog" # 存储文档的文件夹路径
    create: true # 允许用户在此集合中创建新文档
    slug: "{{slug}}" # 标题.md
    editor:
    preview: false
    fields: # 每个文档的字段，通常在front matter中
      - { label: "布局", name: "layout", widget: "hidden", default: "blog" }
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "缩略图", name: "thumbnail", widget: "image" }
      - { label: "评分（1-5 的范围）", name: "rating", widget: "number" }
      - { label: "正文", name: "body", widget: "markdown" }
